---
ansible_user: nqhuy25
ansible_user_home: "/home/{{ ansible_user }}"

# Common directories
autostart_dir: "{{ ansible_user_home }}/.config/autostart"

# Gnome extensions
gnome_extension_dir: "{{ ansible_user_home }}/.local/share/gnome-shell/extensions"
