---
apt_common_packages:
  - build-essential
  - curl
  - git
  - wget
  - unzip
  - fzf
  - exa
  - ansible
  - bat
  - neofetch

apt_extra_packages:
  - brave-browser
  - copyq
  - flameshot
  - zsh
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
