---
- name: Install docker-related packages
  apt:
    name: "{{ apt_docker_packages }}"
    state: present

- name: Add current user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Enable and start docker service
  service:
    name: docker
    state: started
    enabled: true
