---
- name: Ensure required dependencies are installed
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present
  become: true

- name: Download Tabby repository setup script
  get_url:
    url: https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh
    dest: /tmp/tabby-repo-setup.sh
    mode: "0755"

- name: Execute Tabby repository setup script
  command: /tmp/tabby-repo-setup.sh
  become: true

- name: Update package cache
  apt:
    update_cache: yes
  become: true

- name: Install Tabby terminal
  apt:
    name: tabby-terminal
    state: present
  become: true
