---
- name: Ensure required dependencies are installed
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present

- name: Add Tabby repository and install Tabby
  shell: |
    curl -s https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | bash
  args:
    executable: /bin/bash
