---
- name: Ensure zsh is installed
  apt:
    name: zsh
    state: present

- name: Install oh-my-zsh if needed
  become_user: "{{ ansible_user }}"
  shell: |
    if [ ! -d "$HOME/.oh-my-zsh" ]; then
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    fi
  args:
    executable: /bin/bash
  changed_when: false
