- hosts: local
  become: true
  user: "{{ ansible_user }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/apt.yml
    - group_vars/snap.yml
  roles:
    - common
    - shell
    - gnome
    - devtools
    - autostart
