---
- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Change default shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ default_shell }}"
  when: default_shell != ansible_env.SHELL

- name: Install Oh My Zsh (if enabled)
  shell: |
    if [ ! -d "$HOME/.oh-my-zsh" ] && {{ oh_my_zsh_install|bool }}; then
      sh -c "$(curl -fsSL {{ oh_my_zsh_install_url }})" "" --unattended
    fi