---
- name: Ensure autostart directory exists
  file:
    path: "{{ autostart_dir }}"
    state: directory
    mode: "0755"

- name: Deploy .desktop files using templates
  template:
    src: "{{ item.src }}"
    dest: "{{ autostart_dir }}/{{ item.dest }}"
    mode: "0644"
  with_items: "{{ desktop_templates }}"
