---
- name: Install APT packages
  apt:
    name: "{{ apt_packages }}"
    state: present

- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present

- name: Install snap packages
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic|default(false) }}"
    state: present
  loop: "{{ snap_packages }}"