---
zsh_theme: "spaceship"
zsh_theme_dir: "spaceship-prompt"
zsh_theme_repo: https://github.com/spaceship-prompt/spaceship-prompt.git

zsh_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
  - name: zsh-bat
    repo: https://github.com/fdellwing/zsh-bat.git
  - name: you-should-use
    repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
