---
# Ensure prerequisites are installed
- name: Install required system packages
  become: true
  apt:
    name:
      - git
      - make
      - gettext
      - jq
      - unzip
      - gnome-shell
      - gnome-shell-common
      - gnome-shell-extension-manager
      - gnome-shell-extension-prefs
      - gnome-shell-extension-appindicator
      - gnome-shell-extensions
      - gnome-tweaks
    state: present
    update_cache: yes
