---
- name: Install required system packages
  apt:
    name:
      - git
      - make
      - gettext
      - gnome-shell
      - gnome-shell-common
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-desktop-icons-ng
      - gnome-shell-extension-manager
      - gnome-shell-extension-prefs
      - gnome-shell-extension-ubuntu-dock
      - gnome-shell-extensions
      - gnome-shell-extension-prefs
      - gnome-shell-extension-appindicator
    state: present
    update_cache: yes

- name: Install dependencies for building GNOME extensions
  become: true
  package:
    name:
      - jq
    state: present
