- name: Create GNOME extensions directory
  file:
    path: "{{ gnome_extension_dir }}"
    state: directory
    mode: "0755"
  run_once: true

- name: Install GNOME extensions
  block:
    - name: Download GNOME extension zip
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.name }}.zip"
        mode: "0644"
      loop: "{{ gnome_extensions }}"

    - name: Extract GNOME extension
      unarchive:
        src: "/tmp/{{ item.name }}.zip"
        dest: "{{ gnome_extension_dir }}"
        creates: "{{ gnome_extension_dir }}/{{ item.name }}"
      when: item.url is defined
      loop: "{{ gnome_extensions }}"

    - name: Enable GNOME extension
      command: "gnome-extensions enable {{ item.uuid }}"
      loop: "{{ gnome_extensions }}"
      when:
        - item.enable | default(false)
        - item.uuid is defined
      changed_when: "'{{ item.uuid }}' not in command('gnome-extensions list --enabled', warn=False, failed_when=False).stdout"
