#!/usr/bin/env bash

# inventory_device.sh
# This script generates inventory.yml from the current device’s state.

set -e
cd "$(dirname "$0")/.."

INVENTORY_FILE="inventory.yml"

echo "Collecting system inventory..."

# Get installed APT packages (excluding libraries starting with lib to reduce noise,
# but you can adjust this filter as needed)
APT_PACKAGES=$(dpkg -l | awk '/^ii/ && $2 !~ /^lib/ {print $2}')

# Get installed snap packages
SNAP_PACKAGES=$(snap list | awk 'NR>1 {print $1}')

# Create the inventory.yml file
# Note: You can further customize filters, e.g., exclude certain known packages.
{
    echo "# Automatically generated by inventory_device.sh"
    echo "discovered_apt_packages:"
    for pkg in $APT_PACKAGES; do
        echo "  - $pkg"
    done
    echo
    echo "discovered_snap_packages:"
    for pkg in $SNAP_PACKAGES; do
        echo "  - $pkg"
    done
} > $INVENTORY_FILE

echo "Inventory written to $INVENTORY_FILE"
echo "You may review and edit this file before running the Ansible playbook."
